repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-yaml
        # Overlays are deliberately multi-doc
        exclude: "^tests/integration/bundle/test-overlays/.*multi.*yaml$"
      - id: check-toml
      - id: mixed-line-ending
      - id: end-of-file-fixer
        exclude: "^juju/client/schemas-juju.*json$"
      - id: trailing-whitespace
      - id: detect-private-key
        exclude: "^tests/.*$"
  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: [ --preview, --fix ]
      - id: ruff-format
        args: [ --preview ]
  # Spellcheck the code.
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
      exclude: "^juju/client/schemas-juju.*json$"
ci:
  autofix_prs: false
