from typing import List, Protocol

from juju.client._definitions import (
    ApplicationGetResults,
    ApplicationInfoResults,
    Entity,
)


class ApplicationFacadeProtocol(Protocol):
    async def Get(self, application=None, branch=None) -> ApplicationGetResults: ...

    # jRRC Params={"entities":[{"tag": "yada-yada"}]}
    # codegen unpacks top-level keys into keyword arguments
    async def ApplicationsInfo(self, entities: List[Entity]) -> ApplicationInfoResults: ...

    # etc...
    # etc...
    # etc...
    # etc...
    # etc...
    # etc...


class CharmsFacadeProtocol(Protocol):
    ...


class UniterFacadeProtocol(Protocol):
    ...
